// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GymManagementSystem.Models;

[Table("WorkOutProgram")]
[Index("CoachID", Name = "IDX_Program_Coach")]
public partial class WorkOutProgram
{
    [Key]
    public int ID { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [StringLength(500)]
    public string Description { get; set; }

    public int? CoachID { get; set; }

    [InverseProperty("Program")]
    public virtual ICollection<Class> Classes { get; set; } = new List<Class>();

    [ForeignKey("CoachID")]
    [InverseProperty("WorkOutPrograms")]
    public virtual Coach Coach { get; set; }
}

